import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import BottomBar from "@/components/BottomBar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light">
      <body className={`${inter.className} bg-[#F8F8F6]`}>
        <Navbar />

        {/* Sidebar only on large screens */}
        <div className="hidden xl:block">
          <Sidebar />
        </div>

        {/* Main content with margin for sidebar */}
        <main className="min-h-screen max-w-7xl mx-auto">
          {children}
        </main>

        {/* Footer (optional, you can keep/remove depending on design) */}
        {/* <footer className="bg-red-300 text-center py-2">Hello</footer> */}

        {/* Bottom bar only on mobile/tablet */}
        <div className="xl:hidden">
          <BottomBar />
        </div>
      </body>
    </html>
  );
}
