import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light" >
      <body
        className={`${geistSans.variable} bg-[#F8F8F6] ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main className="  min-h-screen ">
          {children}
        </main>
        <footer className="bg-red-300">
          Hello
        </footer>
      </body>
    </html>
  );
}
