import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light" >
      <body
        className={`${inter.className} bg-[#F8F8F6]`}
      >
        <Navbar />
        <Sidebar/>
        <main className="  min-h-screen ">
          {children}
        </main>
        <footer className="bg-red-300">
          Hello
        </footer>
      </body>
    </html>
  );
}
