export const schemes = [
  {
    id: "scheme_001",
    name: "PM-KISAN Scheme",
    status: "Active",
    description: "Direct income support of Rs. 6000 per year in 3 equal installments.",
    amount: "6,000/year",
    duration: "Open throughout the year",
    category: "Financial Assistance",
    eligibility: ["Small & Marginal Farmers", "Land ownership required", "Valid Aadhaar card"],
    state: "All India",
    ministry: "Ministry of Agriculture",
    applyLink: "/apply/pm-kisan",
    detailLink: "/details/pm-kisan"
  },
  {
    id: "scheme_002",
    name: "Soil Health Card Scheme",
    status: "Active",
    description: "Free soil testing and nutrient management recommendations for farmers.",
    amount: "Free Service",
    duration: "Ongoing",
    category: "Technical Support",
    eligibility: ["All farmers"],
    state: "All India",
    ministry: "Ministry of Agriculture",
    applyLink: "/apply/soil-health-card",
    detailLink: "/details/soil-health-card"
  },
  {
    id: "scheme_003",
    name: "Pradhan Mantri Fasal Bima Yojana",
    status: "Active",
    description: "Crop insurance providing financial support to farmers suffering crop loss.",
    amount: "Up to 2,00,000",
    duration: "Before sowing season",
    category: "Insurance",
    eligibility: ["All farmers growing notified crops"],
    state: "All India",
    ministry: "Ministry of Agriculture",
    applyLink: "/apply/pmfby",
    detailLink: "/details/pmfby"
  },
  {
    id: "scheme_004",
    name: "Organic Farming Scheme",
    status: "Active",
    description: "Financial assistance for conversion to organic farming practices.",
    amount: "50,000/hectare",
    duration: "31st March 2024",
    category: "Subsidies",
    eligibility: ["Farmers willing to convert to organic"],
    state: "All India",
    ministry: "Ministry of Agriculture",
    applyLink: "/apply/organic-farming",
    detailLink: "/details/organic-farming"
  },
  {
    id: "scheme_005",
    name: "Digital Agriculture Mission",
    status: "Upcoming",
    description: "Support for digital technology adoption in agriculture.",
    amount: "75,000 subsidy",
    duration: "15th April 2024",
    category: "Technology",
    eligibility: ["Progressive farmers", "Farmer Producer Organizations"],
    state: "All India",
    ministry: "Ministry of Agriculture",
    applyLink: "/apply/digital-agriculture",
    detailLink: "/details/digital-agriculture"
  },
  {
    id: "scheme_006",
    name: "Kisan Credit Card",
    status: "Active",
    description: "Easy access to credit for farmers' agricultural needs.",
    amount: "Up to 3,00,000",
    duration: "Open Application",
    category: "Financial Assistance",
    eligibility: ["Farmers with land documents"],
    state: "All India",
    ministry: "Ministry of Agriculture",
    applyLink: "/apply/kisan-credit-card",
    detailLink: "/details/kisan-credit-card"
  },
  {
    id: "scheme_007",
    name: "Mukhya Mantri Kisan Samman Nidhi",
    status: "Active",
    description: "Financial support of 4,000 per year for small and marginal farmers in Punjab.",
    amount: "4,000/year",
    duration: "Open Application",
    category: "Financial Assistance",
    eligibility: ["Small & Marginal Farmers in Punjab"],
    state: "Punjab",
    ministry: "Punjab State Govt",
    applyLink: "/apply/punjab-kisan-samman",
    detailLink: "/details/punjab-kisan-samman"
  },
  {
    id: "scheme_008",
    name: "Gujarat Organic Farming Assistance",
    status: "Active",
    description: "Financial aid for farmers in Gujarat adopting organic practices.",
    amount: "40,000/hectare",
    duration: "31st March 2024",
    category: "Subsidies",
    eligibility: ["Farmers in Gujarat converting to organic farming"],
    state: "Gujarat",
    ministry: "Gujarat State Govt",
    applyLink: "/apply/gujarat-organic",
    detailLink: "/details/gujarat-organic"
  },
  {
    id: "scheme_009",
    name: "Punjab Soil Health Initiative",
    status: "Active",
    description: "Free soil testing and tailored recommendations for Punjab farmers.",
    amount: "Free Service",
    duration: "Ongoing",
    category: "Technical Support",
    eligibility: ["All farmers in Punjab"],
    state: "Punjab",
    ministry: "Punjab State Govt",
    applyLink: "/apply/punjab-soil-health",
    detailLink: "/details/punjab-soil-health"
  },
  {
    id: "scheme_010",
    name: "Gujarat Kisan Sahay Yojana",
    status: "Active",
    description: "Crop insurance and disaster relief support for Gujarat farmers.",
    amount: "Up to 1,50,000",
    duration: "Before sowing season",
    category: "Insurance",
    eligibility: ["Farmers growing notified crops in Gujarat"],
    state: "Gujarat",
    ministry: "Gujarat State Govt",
    applyLink: "/apply/gujarat-kisan-sahay",
    detailLink: "/details/gujarat-kisan-sahay"
  }
];
